export const SeatsArrangementMockData= {
    screenConfiguration:
 {
    "status":{
       "code":200,
       "message":"Data detail"
    },
    "data":{
       "_id":"5fa86469f40d7a09f414afb0",
       "numberOfScreens":1,
       "screenData":[
          {
             "sectionData":[
                {
                   "nameOfSeat":[
                      
                   ],
                   "seatsInRow":[
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afb3",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      },
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afb4",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      },
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afb5",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      }
                   ],
                   "seats":[
                      {
                         "rowsName":"A",
                         "seatsInRow":[
                            "A1",
                            "A2",
                            "A3",
                            "A4",
                            "A5",
                            "A6",
                            "A7",
                            "A8",
                            "A9",
                            "A10",
                            "A11",
                            "A12",
                            "A13",
                            "A14",
                            "A15",
                            "A16",
                            "A17",
                            "A18",
                            "A19",
                            "A20"
                         ]
                      },
                      {
                         "rowsName":"B",
                         "seatsInRow":[
                            "B1",
                            "B2",
                            "B3",
                            "B4",
                            "B5",
                            "B6",
                            "B7",
                            "B8",
                            "B9",
                            "B10",
                            "B11",
                            "B12",
                            "B13",
                            "B14",
                            "B15",
                            "B16",
                            "B17",
                            "B18",
                            "B19",
                            "B20"
                         ]
                      },
                      {
                         "rowsName":"C",
                         "seatsInRow":[
                            "C1",
                            "C2",
                            "C3",
                            "C4",
                            "C5",
                            "C6",
                            "C7",
                            "C8",
                            "C9",
                            "C10",
                            "C11",
                            "C12",
                            "C13",
                            "C14",
                            "C15",
                            "C16",
                            "C17",
                            "C18",
                            "C19",
                            "C20"
                         ]
                      }
                   ],
                   "_id":"5fa86469f40d7a09f414afb2",
                   "name":"Gold",
                   "numberOfRows":3
                },
                {
                   "nameOfSeat":[
                      
                   ],
                   "seatsInRow":[
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afb7",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      },
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afb8",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      },
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afb9",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      }
                   ],
                   "_id":"5fa86469f40d7a09f414afb6",
                   "name":"Silver",
                   "seats":[
                      {
                         "rowsName":"D",
                         "seatsInRow":[
                            "D1",
                            "D2",
                            "D3",
                            "D4",
                            "D5",
                            "D6",
                            "D7",
                            "D8",
                            "D9",
                            "D10",
                            "D11",
                            "D12",
                            "D13",
                            "D14",
                            "D15",
                            "D16",
                            "D17",
                            "D18",
                            "D19",
                            "D20"
                         ]
                      },
                      {
                         "rowsName":"E",
                         "seatsInRow":[
                            "E1",
                            "E2",
                            "E3",
                            "E4",
                            "E5",
                            "E6",
                            "E7",
                            "E8",
                            "E9",
                            "E10",
                            "E11",
                            "E12",
                            "E13",
                            "E14",
                            "E15",
                            "E16",
                            "E17",
                            "E18",
                            "E19",
                            "E20"
                         ]
                      },
                      {
                         "rowsName":"F",
                         "seatsInRow":[
                            "F1",
                            "F2",
                            "F3",
                            "F4",
                            "F5",
                            "F6",
                            "F7",
                            "F8",
                            "F9",
                            "F10",
                            "F11",
                            "F12",
                            "F13",
                            "F14",
                            "F15",
                            "F16",
                            "F17",
                            "F18",
                            "F19",
                            "F20"
                         ]
                      }
                   ],
                   "numberOfRows":3
                },
                {
                   "nameOfSeat":[
                      
                   ],
                   "seatsInRow":[
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afbb",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      },
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afbc",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      },
                      {
                         "emptySpaces":[
                            1,
                            2,
                            5,
                            9
                         ],
                         "_id":"5fa86469f40d7a09f414afbd",
                         "numberOfSeatsInRow":20,
                         "totalSeatSpaces":24
                      }
                   ],
                   "_id":"5fa86469f40d7a09f414afba",
                   "name":"Bronze",
                   "numberOfRows":3,
                   "seats":[
                      {
                         "rowsName":"G",
                         "seatsInRow":[
                            "G1",
                            "G2",
                            "G3",
                            "G4",
                            "G5",
                            "G6",
                            "G7",
                            "G8",
                            "G9",
                            "G10",
                            "G11",
                            "G12",
                            "G13",
                            "G14",
                            "G15",
                            "G16",
                            "G17",
                            "G18",
                            "G19",
                            "G20"
                         ]
                      },
                      {
                         "rowsName":"H",
                         "seatsInRow":[
                            "H1",
                            "H2",
                            "H3",
                            "H4",
                            "H5",
                            "H6",
                            "H7",
                            "H8",
                            "H9",
                            "H10",
                            "H11",
                            "H12",
                            "H13",
                            "H14",
                            "H15",
                            "H16",
                            "H17",
                            "H18",
                            "H19",
                            "H20"
                         ]
                      },
                      {
                         "rowsName":"I",
                         "seatsInRow":[
                            "I1",
                            "I2",
                            "I3",
                            "I4",
                            "I5",
                            "I6",
                            "I7",
                            "I8",
                            "I9",
                            "I10",
                            "I11",
                            "I12",
                            "I13",
                            "H14",
                            "I15",
                            "I16",
                            "I17",
                            "I18",
                            "I19",
                            "I20"
                         ]
                      }
                   ]
                }
             ],
             "_id":"5fa86469f40d7a09f414afb1",
             "name":"hall1",
             "numberOfSection":3
          }
       ],
       "__v":0
    }
 },
 screenSchedule:
 {
    "status":{
       "code":200,
       "message":"Data detail"
    },
    "data":[
       {
          "_id":"5fb195884cedd424480f5bb0",
          "screenName":[
             "Hall1",
             "Hall2"
          ],
          "movieDate":"02-12-2020",
          "movieId":"5efa3ef59de42327b0e612ab",
          "screensData":{
             "_id":"5fb195884cedd424480f5bb1",
             "screenId":"5fa86469f40d7a09f414afb1",
             "ticketSectionArray":[
                {
                   "_id":"5fb195884cedd424480f5bb2",
                   "sectionName":"Gold",
                   "ticketPerSection":22
                },
                {
                   "_id":"5fb195884cedd424480f5bb3",
                   "sectionName":"Silver",
                   "ticketPerSection":12
                },
                {
                   "_id":"5fb195884cedd424480f5bb4",
                   "sectionName":"Bronze",
                   "ticketPerSection":11
                }
             ],
             "startDate":"12-11-2020",
             "endDate":"21-11-2020",
             "movieStartTime":"8am"
          },
          "__v":0,
          "movie":[
             {
                "_id":"5efa3ef59de42327b0e612ab",
                "genre":[
                   "Action",
                   "SciFi"
                ],
                "language":[
                   "English",
                   "Hindi"
                ],
                "onlineStatus":true,
                "movieName":" Avengers Infinity War",
                "duration":"2 hrs 42 mins",
                "cast":[
                   {
                      "_id":"5efa3ef59de42327b0e612ac",
                      "actorName":"Robert Downey Jr",
                      "actingName":"Tony Stark",
                      "role":"ACTOR"
                   },
                   {
                      "_id":"5efa3ef59de42327b0e612ad",
                      "actorName":"Chris Evans",
                      "actingName":"Steven Rogers",
                      "role":"ACTOR"
                   }
                ],
                "crew":[
                   {
                      "_id":"5efa3ef59de42327b0e612ae",
                      "crewName":"Josh Whedon",
                      "role":"Director"
                   },
                   {
                      "_id":"5efa3ef59de42327b0e612af",
                      "crewName":"Kevin Feige",
                      "role":"Producer"
                   }
                ],
                "releaseDate":"2018-05-02T18:30:00.000Z",
                "trailerLink":"https://www.youtube.com/watch?v=udKE1ksKWDE",
                "__v":0
             }
          ]
       },
       {
          "_id":"5fb195884cedd424480f5bb0",
          "screenName":[
             "Hall1",
             "Hall2"
          ],
          "movieDate":"02-12-2020",
          "movieId":"5efa3ef59de42327b0e612ab",
          "screensData":{
             "_id":"5fb195884cedd424480f5bb6",
             "screenId":"5fa86469f40d7a09f414afb1",
             "ticketSectionArray":[
                {
                   "_id":"5fb195884cedd424480f5bb2",
                   "sectionName":"Gold",
                   "ticketPerSection":22
                },
                {
                   "_id":"5fb195884cedd424480f5bb3",
                   "sectionName":"Silver",
                   "ticketPerSection":12
                },
                {
                   "_id":"5fb195884cedd424480f5bb4",
                   "sectionName":"Bronze",
                   "ticketPerSection":11
                }
             ],
             "startDate":"12-11-2020",
             "endDate":"21-11-2020",
             "movieStartTime":"12am"
          },
          "__v":0,
          "movie":[
             {
                "_id":"5efa3ef59de42327b0e612ab",
                "genre":[
                   "Action",
                   "SciFi"
                ],
                "language":[
                   "English",
                   "Hindi"
                ],
                "onlineStatus":true,
                "movieName":" Avengers Infinity War",
                "duration":"2 hrs 42 mins",
                "cast":[
                   {
                      "_id":"5efa3ef59de42327b0e612ac",
                      "actorName":"Robert Downey Jr",
                      "actingName":"Tony Stark",
                      "role":"ACTOR"
                   },
                   {
                      "_id":"5efa3ef59de42327b0e612ad",
                      "actorName":"Chris Evans",
                      "actingName":"Steven Rogers",
                      "role":"ACTOR"
                   }
                ],
                "crew":[
                   {
                      "_id":"5efa3ef59de42327b0e612ae",
                      "crewName":"Josh Whedon",
                      "role":"Director"
                   },
                   {
                      "_id":"5efa3ef59de42327b0e612af",
                      "crewName":"Kevin Feige",
                      "role":"Producer"
                   }
                ],
                "releaseDate":"2018-05-02T18:30:00.000Z",
                "trailerLink":"https://www.youtube.com/watch?v=udKE1ksKWDE",
                "__v":0
             }
          ]
       }
    ]
 }

  }


 