module.exports.message = {
	LOGIN_SUCCESS: "Login successfully.",
	CREADTED: "Data created.",
	INTERNAL_ERROR: "Internal server error occured.",
	NOT_FOUND: "Data not found.",
	REQUIRED_FIELDS: "Please fill required field.",
	EXIST: "Data already exist.",
	LIST_DATA: "List of all data.", 
	CONFIRM_DELETE: "Do you want to delete ?",
	UNAUTH_ACCESS: "Unauthorized access.",
	WRONG_CRED: "Email or password is incorrect.",
	DETAIL: "Data detail",
	DELETED: "Data deleted successfully.",
	UNIQUE_CODE: "Unique code.",
	USER_EXIST: "Username taken already.",
	EMAIL_VERIFY: "Email verified successfully.",
	UPDATED: "Data updated successfully.",
	NO_FILE: "No file selected.",
	EXCEPTION: "Exceaptional error.",
	WRONG_FILE_EXT: "Wrong File Extension.",
	NO_TOKEN: "Failed to authenticate token. No token found",
	INCORRECT_TOKEN : "Token is incorrect",
	REFRESH_TOKEN : "Token is expired",
	SIGNUP_SUCCESS: "An email has been sent. Please verify to continue.",
	NO_EMAIL: 'Error to send email.',
	COURSE_CREADTED: "Course added successfully.",
	SLIDE_LIST: "List course slide",
	PASSWORD_NOT_SENT: "Email could not be sent. Please try again later.",
	PASSWORD_SENT: "Email has been sent to you. Please check and login.",
	VERIFY_UR_EMAIL: "Please verify your email then try again.",
	EMAIL_VERIFIED: "You are already verified.",
	USER_DELETED: "User deleted successfully.",
	COURSE_DELETED: "Course deleted successfully.",
	CATEGORY_DELETED: "Category deleted successfully.",
	SLIDE_DELETED: "Slide deleted successfully.",
	USER_ADDED: "User has been added successfully.",
	CATEGORY_CREATED: "Category created successfully.",
	COURSE_UPDATED: "Course updated successfully.",
	USER_NAME_EXIST: "Username exists already",
	USER_EMAIL_EXIST: "User email exists already",
	COURSE_EXIST: "Course exists already",
	SLIDE_EXIST: "Slide code exists already. Please use another slide code.",
	ROOT_EXISTS_ALLREADY: "Please select the parent category",
	CANT_ASSIGN_PARENT: "We can have only one root.",
	SLIDE_CREADTED: "Slide created successfully.",
	SLIDE_UPDATED: "Slide updated successfully.",
	CATEGORY_UPDATED: "Course category updated successfully.",
	USER_COURSE_STATS_UPDATED : "User course stats updated successfully.",
	EVENT_UPDATED : "Slide Event updated successfully",
	EVENT_DELETED : "Slide Event deleted successfully",
	USER_COURSE_SLIDE_STATS_UPDATED : "User course slide stats updated successfully.",
	COURSE_NOT_COMPLETED : "User course is not completed.",
	DATABASE_SAVED : "Database backup save successfully"
}
